### PR TITLE
changed to gradle google support dependencies

### PR DESCRIPTION
**Pull request by kibotu**

### CODE REVIEW

**Comment by JohnKiller** [comment]
I'm testing it now, if it works it also solves #52 and #55

**Comment by kibotu** [comment]
all right, let me know if something is wrong

**Comment by JohnKiller** [comment]
Works perfectly. Thanks.

Hoping this will be merged!

**Comment by HugoHeneault** [comment]
Any news about merging this ? :3

**Comment by guacachips** [comment]
Thank you so much ! It's working perfectly now :)

**Comment by petr001** [comment]
Hi, can be this merged? It's one year from confirming that it works well :)

**Pull request merged**
